### ISSUE TITLE
Find services registered after discovery is started

### ISSUE THREAD

**Issue by kostadin24** [sebastianhaberey/nsd#12]
Hi
In my Flutter app I have case when new services are registered and they are not discovered by mdns discovery. This happens in about 10-20% of tests. If I stop and start discovery - they appear.

So only approach is to implement restart of discovery browsers OR this is a bug.

**Comment by sebastianhaberey** [comment]
Hi @kostadin24,

strange - I've never seen this behaviour, neither in the example application, nor in the integration test which routinely starts 10 services and waits for all of them to be discovered.

Maybe you are not waiting long enough? When you start a service it will take a while until it is discovered. The list `discovery.services` changes over time. Take the code from the example:

```Dart
discovery.addListener(() {
  // discovery.services contains discovered services
});
```

The listener will be called every time the list changes. So it will be called once after the first service is added, once after the second service is added, once after the first service is removed, once after the second service is removed. Depending on when you look at the list, it may not contain all the services you expect.

**Comment by kostadin24** [comment]
This is what I do.
But may be mDNS in local devices is not working good. Didn't observe this when browse for standard services over network.
It happens when search for my devices, they have custom mDNS implementation. Starting and stopping mdns browser 
helps. But still not sure what is reason.
