### ISSUE TITLE
Kotlin Compiler Error

### ISSUE THREAD

**Issue by chrislenguyen** [sebastianhaberey/nsd#14]
Hi, i am using your package and run into this error below when building the application. 

======================================================

Conflicting overloads: internal fun deserializeHandle(arguments: Map<String, Any?>?): String? defined in com.haberey.flutter.nsd_android in file Serialization.kt, internal fun deserializeHandle(arguments: Map<String, Any?>?): String? defined in com.haberey.flutter.nsd_android in file Serialization.kt

* What went wrong:
Execution failed for task ':nsd_android:compileDebugKotlin'.
Compilation error. See log for more details

======================================================

I'm currently using flutter version 2.10.4. Below is my flutter doctor

[√] Flutter (Channel unknown, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.66.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

Could you check it for me, thanks a lot

**Comment by sebastianhaberey** [comment]
Hi @chrislenguyen,

I just did a fresh install of the current main on a new machine and it works fine out of the box. Also, the integration tests are succeeding. What is it you're working on? 

a] compile and run nsd example application
b] use nsd plugin in own project
c] ?

**Comment by chrislenguyen** [comment]
Hi @sebastianhaberey , 

I am currently using it in my project

I have found a solution to fix it, I cloned your whole package and make a change here 

The current one on github:
![image](https://user-images.githubusercontent.com/34916267/162164574-d8b98c72-42fd-43e9-8586-2532877fa727.png)

The change I made:
<img width="743" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/34916267/162164882-e1a0159b-0952-4010-85d4-fb78a6336da4.png">

I only change the error displayed on my computer console, if you happen to understand what's going on can you please explain it to me.  

Again, thank you very much

**Comment by sebastianhaberey** [comment]
I'll try to reproduce your error and see what I can find out. Could you post the output of `flutter doctor -v`?

**Comment by chrislenguyen** [comment]
Here is my `flutter doctor -v` result:

[√] Flutter (Channel unknown, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
    • Flutter version 2.10.4 at C:\Users\khuong\flutter
    • Upstream repository unknown
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Windows (desktop)   • windows             • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)        • chrome              • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)          • edge                • web-javascript • Microsoft Edge 100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by sebastianhaberey** [comment]
To be honest, I could not reproduce the error on my machine. I also do not see a logical reason why `deserializeServiceInfo` would need to allow null arguments in order to fix an error concerning `deserializeHandle`.

That said, I decided to incorporate the change, since it's backward compatible and it harmonizes the `deserializeXXX` methods (the other methods also allow null).

I published a new version of the plugin (1.4.3), please try if it works on your machine.

**Comment by chrislenguyen** [comment]
I have tested the example and applied it to my project and it worked well. Thank you so much for your help, I will close this issue now.
