### ISSUE TITLE
iOS: onDiscoveryStartFailed

### ISSUE THREAD

**Issue by robert-virkus** [sebastianhaberey/nsd#16]
Hi, is there anything I need to set up on iOS for being able to start scanning?

My code:
```dart
nsd.enableLogging(nsd.LogTopic.calls);
nsd.enableLogging(nsd.LogTopic.errors);
nsd.startDiscovery('_ds-prov._tcp').then((discovery) {
// ...
});
```

log output:
```
[MethodChannelNsdPlatform] [2022-04-25 16:50:18.712895] [calls] Call: startDiscovery {handle: d4dd15f0-6bf0-4e4f-9ba3-bf789c808402, service.type: _ds-prov._tcp}
[MethodChannelNsdPlatform] [2022-04-25 16:50:18.731574] [calls] Callback: onDiscoveryStartFailed {handle: d4dd15f0-6bf0-4e4f-9ba3-bf789c808402}
```

The same code works fine on Android, on iOS I receive the above log output: `onDiscoveryStartFailed`.

Many thanks in advance and thanks for your cool nsd library!

**Comment by robert-virkus** [comment]
I was missing the following settings in my `Info.plist` file:
```xml
<key>NSLocalNetworkUsageDescription</key>
<string>To discover network devices via mDNS</string>
<key>NSBonjourServices</key>
<array>
	<string>_ds-prov._tcp</string>
</array>
```

It would be useful to mention this in your readme (not with this specific service type, of course).

Thanks again for your library!

**Comment by sebastianhaberey** [comment]
Yes, you're absolutely right, I'll add this to the README.

**Comment by sebastianhaberey** [comment]
I've updated the documentation and put the permission chapter in a more prominent place. Also, I added the permissions to the iOS version of the example app. Tests are green and the new version is out (1.5.0) so I'm closing this. Thank you for your contribution 🙂
