### ISSUE TITLE
track flutter.compileSdkVersion with nsd_android/android/build.gradle compileSdkVersion?

### ISSUE THREAD

**Issue by repentsinner** [sebastianhaberey/nsd#17]
Should the compileSdkVersion in `nsd_android/android/build.gradle` be reverted to 31 along with the change in f7a891a1cb078c50ec997b55174ea17d19563b09? I'm getting a build warning:

> Warning: The plugin nsd_android requires Android SDK version 32.

Thanks!

**Comment by sebastianhaberey** [comment]
Hi @repentsinner,

are you attempting to compile the plugin / example with an Android SDK below 32? 

If that's the case, just update your SDK to 32 and you should be fine. It is strongly recommended that you always compile with the latest SDK - [see this Article by Ian Lake (Google)](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd).

P.S.: that reminds me, I should add the minimum requirements for the plugin to the README.

**Comment by repentsinner** [comment]
Thanks for the quick reply @sebastianhaberey. I'm using boilerplate `build.gradle` which pulls compileSdkVersion from flutter:

```
android {
  compileSdkVersion flutter.compileSdkVersion
  ...
}
```

Over in the flutter source for stable (as of today, 2.10.5), flutter.compileSdkVersion is (still) defined as 31:

https://github.com/flutter/flutter/blob/5464c5bac742001448fe4fc0597be939379f88ea/packages/flutter_tools/gradle/flutter.gradle#L32-L33


I had a quick look through the issues and other tags/branches and I don't see much discussion/attempt to move it to 32 which to your point and Google best practices does seem odd.

If nsd requires a feature of 32 and the main flutter distribution is still using 31, it might be worth making a note in the docs that this should be overridden (but you updated to note that it only requires min 21). If not, does it make sense to just track flutter.compileSdkVersion in nsd's build.gradle so that it'll work with whatever's current, and puts the onus on flutter to correctly manage SdkVersions?

**Comment by sebastianhaberey** [comment]
First off, you're right - I didn't consider that a freshly generated app would have a `compileSdkVersion` assigned by Flutter, and that most users would just have that version pulled automatically.

Also, I agree that it would be nice to have something like `flutter.compileSdkVersion` in the plugin to avoid having to update the Gradle configuration manually once Flutter changes their version. Unfortunately, that property doesn't seem to be available for plugins - the Gradle configuration for plugins is different from the one generated for applications.

It seems that the Flutter team is maintaining the `compileSdkVersion` of their [plugin favorites](https://github.com/flutter/plugins/tree/main/packages) manually to match the Flutter version. So until I learn of a better way, I guess I'll be doing the same.

Please give the new version (1.5.3) a try and see if it works for you!

**Comment by repentsinner** [comment]
Looks good to me, thanks!

FWIW I opened an issue on the main flutter project to ask why they're still using SDK 31, curious what they say about that.

https://github.com/flutter/flutter/issues/103713
