### ISSUE TITLE
`MissingPluginException` only on release mode `NSDError(Message: "MissingPluginImplementation" found for method register on channel com.haberey/nsd", cause: InternalError)`

### ISSUE THREAD

**Issue by lakscastro** [sebastianhaberey/nsd#18]
> All tests/runs are done by using real devices

## Environment

- Flutter

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19043.1706], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.13)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

- Dart 

```
Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "windows_x64"
```

### Tested devices:

- Samsung Galaxy A30

```
Samsung Exynos 7 Octa 7904 (14 nm)
Octa-core, 1800 MHz, ARM Cortex-A73 and ARM Cortex-A53, 64-bit
Mali-G71 MP2
4GB LPDDR4
64GB, available to use: 49.6 GB
microSDXC up to 512 GB
Android 11, Samsung One UI
```

- Xiaomi M4 PRO

```
MediaTek Dimensity 810 5G MT6833 (6 nm)
Octa-core, 2400 MHz, Cortex-A76, 64-bit
Mali-G57 MC2
4GB LPDDR4
128GB Storage
microSDXC up to 1024 GB
Smartphone
Android (11), MIUI 12.5 UI
```

## Context

This is a "Join Room" page.

That is, this page calls `startDiscovery` on init and `stopDiscovery` on dispose.

And it list all available services on the local network.

**The plugin works fine when debug and profile mode.**

But the plugin throws this exception in **release mode**

```dart
// I'm using `flutter_hooks` to widget manage state/lifecycle (cause I use a lot of `AnimationControllers`)
useEffect(
  () {
    // Equivalent to `initState()`
    Discovery? discovery;

    void updateServices() => services.value = discovery!.services;

    Future<void> discoveryServices() async {
      discovery = await startDiscovery(kServiceType, autoResolve: false);

      discovery?.addListener(updateServices);

      updateServices();

      isLoading.value = false;
    }

    discoveryServices();

    // The return function is equivalent to `dispose()`
    return () async {
      if (discovery != null) await stopDiscovery(discovery!);

      discovery?.removeListener(updateServices);
      discovery?.dispose();
    };
  },
  const [],
);
```

This print is from the page `Create Room` which is the opposite of `Join Room` but the same error/exception is thrown

<kbd>
  <img src="https://user-images.githubusercontent.com/51419598/169373820-eb51edad-e19e-43c7-9beb-a8c3cb4888b0.png" height="500">
</kbd>

I already have tried:

- `flutter build apk --no-shrink`
- This one either:
```yaml
minifyEnabled false
shrinkResources false
```

**Comment by sebastianhaberey** [comment]
Yes, I was able to reproduce this on the example app (release mode). Looking into it now.

**Comment by sebastianhaberey** [comment]
In the example application, the problem was a missing permission (`android.permission.INTERNET`). I have fixed this in the example app and updated the README accordingly. Please try adding the permission to your manifest and see if it works for you!

**Comment by lakscastro** [comment]
Is it. Fixed here.

Huge thanks for the fast reply and fix. I'll close it for now.

**Comment by lakscastro** [comment]
@sebastianhaberey I don't know if it's applicable but I created a project that uses nsd package to create a local multiplayer game: [lakscastro/ttt](https://github.com/lakscastro/ttt) maybe you can use it as show-case.

**Comment by sebastianhaberey** [comment]
That's a nice idea! I added a little "Projects using nsd" section to the readme.
