### ISSUE TITLE
Check Windows Version on startup

### ISSUE THREAD

**Issue by xmine64** [sebastianhaberey/nsd#22]
### Description

Is it possible to check Windows version on startup, and don't call unsupported APIs on lower versions of Windows? My app crashes on older versions of Windows because there's no DnsServiceConstructInstance in DNSAPI.dll, if you could add a version check before calling that it would be fine just discovery service won't work, instead of crashing.

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

Windows

**Comment by sebastianhaberey** [comment]
I've added a system requirements check for Windows: `startDiscovery()` and `register()` now throw a `NsdError` with cause `operationNotSupported` if the OS doesn't match requirements. This way you can catch the error and react in your application accordingly (or just ignore it). Please try the new version (2.2.2) and see if this helps you.

**Comment by sebastianhaberey** [comment]
Fixed missing enum, so version 2.2.3 it is.

**Comment by xmine64** [comment]
Thanks.
