### ISSUE TITLE
MacOS CFNetServiceCreateTXTDataWithDictionary can't parse large Value (more than 255 bytes)

### ISSUE THREAD

**Issue by vickyleu** [sebastianhaberey/nsd#24]
### Description

flutterTxtToNativeTxt CFNetServiceCreateTXTDataWithDictionary(nil, nativeData as CFDictionary) return nil,

raw data is 
`{"accessKey":"","extra":"xxxxxxxx~~~~~~~"}`
```
let nativeData : [String:Data]  = flutterTxt.compactMapValues { $0?.data }.mapValues { data in
        let str = String(data: data, encoding: String.Encoding.utf8)
        print("str;;;\(str!)")
       return data
}
```
==>>str;;;203713

str;;;eyJjaXBoZXJUZXh0IjoiM3B4eGxoTXFQRkthZm1JSmU0TzZPWU8zdVNsWkJZVXpTc2pjMEVoS1UyMFgvekJpdkN2dnZ0cldTWHdpY2JjMFBQa2ltVTFVWGltQ0l0eUVBTVo3T1NIVmxxK3dTVlZ4ZFdXSEJMODBNWEt1dkdYbmt5T3pMZUk5WGJPeENpNGxyMUFvS3lKNFdZZzNrdytyR1hVT0dZK3k1MFh6eUU4TnA4UVlsWXRUZGY2WU5hOGRwVkpWekJ0UHRHbXFnVitEbmtJTDFiTmpqT0dRNm14NmVmWW1NcmhYMHdiSDlLamE0WVMzS0U1TG1oWEk4bENXV0UxZmRwVVF5c0pHdWJHenB0OThVeVJpdU5zTjZrWjUvUzROQmtOTjBCR3VZU29pektuWVFibG92ckt3SUtQOG9aWW1NSnpuWWVQSjJVd3E3Qm1BSDlzV2cvc2UxOFVRUkpjUzhtT1g5WHluWnZWaUt5TlhYREl4eE9qSFNuZzRTNzRZNlpGTXhuZFNETkkwaldvN0pFVFF5bmx0NWR1T3VRT0NhU2RSL0pPdEc5RStiSDI0aTVBS3B3ZmxFajJURS8xR3I0TFJkSm53dWlmVmdNSE82Ti8xc21XNkZtN08iLCJtYWMiOiJXcTJGRDRpQ3A4N0d4c01yb0I1ZURBPT0iLCJub25jZSI6IkZzQTVWbTgrWlI1NGNlaEUyQ2hOV010d0t4blRNcForIn0=

`print("CFNetServiceCreateTXTDataWithDictionary==>\(CFNetServiceCreateTXTDataWithDictionary(nil, nativeData as CFDictionary))")`

==>>nil

need to be split into many small values
like 
`{"ac":"less than 255","bc":"less than 255","cd":"less than 255","ef":"less than 255"}`

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

macOS

**Comment by sebastianhaberey** [comment]
Hi @vickyleu 

yes, this is part of the [RFC 6763 DNS-DS specification](https://www.rfc-editor.org/rfc/rfc6763.html#section-6.1):

> The format of each constituent string within the DNS TXT record is a single length byte, followed by **0-255** bytes of text data.

and

> Each key/value pair is encoded as its own constituent string within the DNS TXT record, in the form "key=value" (without the quotation marks).

So the key plus the "=" character plus the value  must not exceed 255 characters **together**.
