### ISSUE TITLE
NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)

### ISSUE THREAD

**Issue by sakAlmahdi** [sebastianhaberey/nsd#26]
### Description

NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)

### Scenario

Use the plugin in my own application via Flutter dependency

**Comment by sebastianhaberey** [comment]
Hi @sakAlmahdi,

the errors thrown by the plugin are documented [here](https://pub.dev/documentation/nsd_platform_interface/latest/nsd_platform_interface/ErrorCause.html):

> maxLimit → const [ErrorCause](https://pub.dev/documentation/nsd_platform_interface/latest/nsd_platform_interface/ErrorCause.html)
>
> Indicates too many "outstanding requests" - on Android (30) this seems to be 10 operations (running discoveries and active registrations combined).

My guess is that you have more than 10 simultaneous discoveries and / or registrations active. Make sure that you stop discoveries you don't need anymore:

```Dart
await stopDiscovery(discovery);
```

Likewise, unregister all services you don't need anymore:

```Dart
await unregister(registration);
```
