### ISSUE TITLE
Expose performIpLookup interface

### ISSUE THREAD

**Issue by andreadaoud** [sebastianhaberey/nsd#27]
### Description

Hi, I would like to convert `xxxxxx.local` address to IP address, but it seems that `performIpLookup` is not exposed. Could you please make it public so I can call it?

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

All of them

**Comment by sebastianhaberey** [comment]
Hi @andreadaoud,

why would you want to call the method directly? You can just specify `IpLookupType.any` when calling [startDiscovery](https://pub.dev/documentation/nsd/latest/nsd/startDiscovery.html). That way the discovered services will contain all their IP addresses. See also [here](https://pub.dev/packages/nsd#get-ip-addresses-for-service).

**Comment by andreadaoud** [comment]
Thank you for your quick response and great work!

On Apple platform we can connect to the service using `xxxxx.local` address. But, on Android, especially older versions, we cannot connect with `.local` address. My use case involves saving the `xxxx.local` address to config file and connect to it later. Running `startDiscovery` every time to get address is an option, but from my point of view, it sounds better to resolve it directly.

**Comment by sebastianhaberey** [comment]
Ok, I get that. And is there any reason why you don't want to use dart:io's [lookup method](https://api.flutter.dev/flutter/dart-io/InternetAddress/lookup.html) directly:

```final addresses = await InternetAddress.lookup(host, type: InternetAddressType.any)```

**Comment by sebastianhaberey** [comment]
Closing this since there seems to be an easy way to do this with basic Flutter functionality. Please feel free to open another issue if this doesn't solve your issue or you're missing anything else!
