### ISSUE TITLE
Max request  reached when discover all service-type

### ISSUE THREAD

**Issue by jet6666** [sebastianhaberey/nsd#28]
### Description

when I discovered all services 
:
`final discovery = await startDiscovery('_services._dns-sd._udp', autoResolve: false);`

there are more than 10 service types : 

if I use  
` 
for ( var type in allTypes ) {
final discovery = await startDiscovery( type );
discovery.addListener(() {
  // discovery.services contains discovered services
});

// ...

await stopDiscovery(discovery);
}

`

there will be an error  : 
`E/flutter (32009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)`

help me how to solve this.  thanks 

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

All of them

**Comment by jet6666** [comment]
solved . use a  timer to loop these types.

**Comment by jet6666** [comment]
Tips: when the new loop start ,close the  discovery instance

**Comment by sebastianhaberey** [comment]
Yes good idea, use a timer and poll the types round-robin style 👍

**Comment by jet6666** [comment]
> Yes good idea, use a timer and poll the types round-robin style 👍

nsd is good plugin ,thanks 👍
