### ISSUE TITLE
TTL support in Service class

### ISSUE THREAD

**Issue by officialdoniald** [sebastianhaberey/nsd#30]
### Description

I can't change the TTL parameter at register method when I register a Service.

### Scenario

Use the plugin in my own application via Flutter dependency

**Comment by sebastianhaberey** [comment]
Hi @officialdoniald,

I could not find an option to specify a TTL - neither in [the Android API](https://developer.android.com/reference/android/net/nsd/NsdManager#registerService(android.net.nsd.NsdServiceInfo,%20int,%20java.util.concurrent.Executor,%20android.net.nsd.NsdManager.RegistrationListener)) nor in the [Apple API](https://developer.apple.com/documentation/foundation/netservice/1414390-publish).

It is therefore simply not possible for the plugin to support TTL.
