### ISSUE TITLE
Initial discovery does not properly detect already registered services.

### ISSUE THREAD

**Issue by Jonas-Schnee** [sebastianhaberey/nsd#33]
### Description

Tested with Android 13 / Windows 10 and the sample app (https://github.com/sebastianhaberey/nsd/tree/main/nsd/example).

Steps to reproduce:

1. Starting the sample app on Windows (as Desktop-App).
2. Register a service with the Windows-Sample-App.
3. Starting another instance of the sample app on an Android 13 device.
4. Start a discovery with the Android-Sample-App. 

Expected: Discovers and shows the Service

Result: No Service is discovered.

5. Register another service with the windows app.
6. The service is shown in the Android app directly. 
7. Using Hot-Restart on the Android App (and starting a new discovery), still only the second service is shown. 
8. Killing the android app instance and restarting it ( and starting a new discovery) no service is shown.

Using "dns-sd -B <type>" now shows both registered services instantly.

Am I doing something wrong? First I thought it is related to my code. But the same issue remains with the sample app as described above. The only thing I changed was the _serviceTypeDiscover_/_serviceTypeRegister_ to "_xxx._tcp".

Is there something I can do to also discover services that were registered before the app was started? 

Thanks

### Scenario

Run the example application

### Platform

Android

**Comment by sebastianhaberey** [comment]
I tried to reproduce this by using Android 12 / Windows 10. But the service is detected instantly on step 4.

Unfortunately I don't have Android 13 on my phone yet, and the Emulator doesn't connect to the real network. I'd be interested if this is an Android 13 issue. You don't happen to have an Android 12 phone lying around that you could try this on for comparison?

**Comment by Jonas-Schnee** [comment]
Hi, sorry for the late reply. I will check tomorrow with android 12 mobile and let you know.

**Comment by Jonas-Schnee** [comment]
Hi @sebastianhaberey 

I do not have the issue any more (checked with an Android 11 phone and again with Android 13 - total confusion ;) ) 

I am not sure what caused the issue as I did not do anything different this time - But I am pretty sure that it is not related to your library but more to my local network/setup. 

I will close this issue for now - Sorry for bothering and thanks for your time.
