### ISSUE TITLE
service name's bug ?

### ISSUE THREAD

**Issue by jet6666** [sebastianhaberey/nsd#36]
### Description

 `[log] new type  = _nvstream_dbd._tcp 
E/flutter (23866): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NsdError (message: "Service type must be in format _<Service>._<Proto>: _nvstream_dbd._tcp", cause: illegalArgument)

E/flutter (23866): #0      MethodChannelNsdPlatform.assertValidServiceType (package:nsd_platform_interface/src/method_channel_nsd_platform.dart:226:7)

E/flutter (23866): #1      MethodChannelNsdPlatform.startDiscovery (package:nsd_platform_interface/src/method_channel_nsd_platform.dart:38:5)

E/flutter (23866): #2      startDiscovery (package:nsd/nsd.dart:31:35)`

the plugin code goes 
`  return RegExp(r'^_[a-zA-Z0-9-]{1,15}._(tcp|udp)').hasMatch(type);`

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

All of them

**Comment by sebastianhaberey** [comment]
Hi @jet6666 

see issue #29 - the specification does not not allow the character "_" in the service name segment. If you don't want to change your service name, you can disable the plugin's service name validation like this:

```Dart
disableServiceTypeValidation(true);
```

I've made a note to myself to document this in the FAQ.

**Comment by jet6666** [comment]
thanks 👍
