### ISSUE TITLE
Error Uint8List not found

### ISSUE THREAD

**Issue by ekokurniadi** [sebastianhaberey/nsd#38]
### Description

![gambar](https://user-images.githubusercontent.com/47097891/223969063-2f9d9db0-7265-4d3a-ad76-d82179d745c5.png)
Hi, i got a error when running my application when using nsd package, errors may be is missing import of dart:typed_data on package nsd_platform_interface

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

Windows

**Comment by sebastianhaberey** [comment]
Hi @ekokurniadi can you run `flutter doctor -v` on your machine and post the results here?

**Comment by ekokurniadi** [comment]
i try to override nsd_platform_interface with forked repo from this repository, and i fixed error with add import dart:typed_data; on nsd_platform_interface, 
![gambar](https://user-images.githubusercontent.com/47097891/224272091-13660094-cede-4eb1-b937-9f66e0ffb4a9.png)

**Comment by sebastianhaberey** [comment]
Happy to see that you fixed it for your setup! But I can not reproduce the error on my side. If you post the output of `flutter doctor -v` here, it might help me to reproduce it.

**Comment by sebastianhaberey** [comment]
Just verified this on Windows to be sure and can confirm It's not an inherent error with the plugin, or missing documentation. The plugin can be used as described in the readme. `dart:typed_data` can be be imported optionally if the client wants to make use of Dart's `UIntList8` type - for example when populating the service's `txt` attribute.
