### ISSUE TITLE
flutter unhandled exception   "Binding has not yet been initialized."   

### ISSUE THREAD

**Issue by jet6666** [sebastianhaberey/nsd#40]
### Description

 
```dart
import 'dart:isolate';

import 'package:flutter/material.dart';
import 'package:multicast_dns/multicast_dns.dart';
import 'package:nsd/nsd.dart';

Future<void> echo(SendPort sender) async {
  var name = '_ipp._tcp';

  final discovery = await startDiscovery(name);
  discovery.addServiceListener((service, status) {
    debugPrint('found service ${service.name}');
  });
// ...

  //await stopDiscovery(discovery);

  debugPrint("echo() the Isolate has been spawned!");
  ReceivePort receivePort = ReceivePort();
  sender.send(receivePort.sendPort);
  receivePort.listen((data) {
    String msg = data[0];
    SendPort replyTo = data[1];
    debugPrint("Isolate received: $msg");

    replyTo.send("Greetings from echo() the Isolate!");
  });
}

Future sendReceive(SendPort port, String msg) {
  ReceivePort receivePort = ReceivePort();
  port.send([msg, receivePort.sendPort]);
  return receivePort.first;
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  ReceivePort receivePort = ReceivePort();
  Future<Isolate> remote = Isolate.spawn(echo, receivePort.sendPort);
  remote.then((_) => receivePort.first).then((sendPort) {
    sendReceive(sendPort, "message sent from main()").then((msg) {
      debugPrint("Main received: $msg");
    });
  });
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: const Center(
        child: Text('some text'),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
 

<details>
<summary>Error</summary>

> ```java

E/flutter (17968): [ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
E/flutter (17968): Binding has not yet been initialized.
E/flutter (17968): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter (17968): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter (17968): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter (17968): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
E/flutter (17968): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:287:9)
E/flutter (17968): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:369:6)
E/flutter (17968): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:55:54)
E/flutter (17968): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:538:51)
E/flutter (17968): #4      new MethodChannelNsdPlatform (package:nsd_platform_interface/src/method_channel_nsd_platform.dart:31:20)
E/flutter (17968): #5      NsdPlatformInterface._instance (package:nsd_platform_interface/src/nsd_platform_interface.dart:18:43)
E/flutter (17968): #6      NsdPlatformInterface._instance (package:nsd_platform_interface/src/nsd_platform_interface.dart)
E/flutter (17968): #7      NsdPlatformInterface.instance (package:nsd_platform_interface/src/nsd_platform_interface.dart:20:47)
E/flutter (17968): #8      startDiscovery (package:nsd/nsd.dart:31:26)
E/flutter (17968): #9      echo (package:flutter_demo3/main.dart:10:27)
E/flutter (17968): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter (17968): #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

```
</details>

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

None

**Comment by sebastianhaberey** [comment]
I am closing this since it has nothing to do with this specific plugin, rather it's a general issue when using isolates with Flutter. From a quick search I did, [this](https://github.com/flutter/flutter/issues/98473#issuecomment-1058500136) might help you:

> anything setting up an isolate where plugins are expected to work should call `DartPluginRegistrant.ensureInitialized()`, which will run all Dart plugin registration.
