### ISSUE TITLE
stopDiscovery Not working giving below exception

### ISSUE THREAD

**Issue by harishkthedeveloper** [sebastianhaberey/nsd#49]
### Description

ERROR: 

NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ #0 MethodChannelNsdPlatform.invoke. (package:nsd_platform_interface/src/method_channel_nsd_platform.dart:201:28)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/1 _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/pull/2 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/3 _FutureListener.handleError (dart:async/future_impl.dart:177:22)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/pull/4 Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/5 Future._propagateToListeners (dart:async/future_impl.dart:799:13)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/pull/6 Future._completeError (dart:async/future_impl.dart:609:5)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/7 _completeOnAsyncError (dart:async-patch/async_patch.dart:272:13)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/8 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter ( 2026): │ https://github.com/Nimrodda/flutter_nsd/issues/9
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ 12:05:02.933 (+0:00:46.781794)
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ ⛔ ERROR OCCURS NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

I've created a custom demo project for to review and reproduce this error:

Clone link - https://github.com/harishkthedeveloper/mdns_demo.git

I've also provided a demo video and log file for your convenience:

Demo video & log file - https://drive.google.com/drive/folders/1cQdpHMdnf3s-ofJ8kjixmOHL55P3AbO8?usp=sharing

To reproduce the issue, please follow these steps:

NOTE: In the file nsd_service.dart, replace String serviceTypeDiscover = "<add_your_service>._tcp"; with your service name.

Click on the "Scan" button to go to the scanned device list page.
Then, click the back button on the Appbar (we are stopping the service in the Dispose method).
Try to switch between Wi-Fi networks in your mobile settings and return to the app.
Repeat the above three steps more than 10 times to encounter the following errors:
Errors:

[MDNS] ERROR: ID:- 4961d42f-eed2-4952-89c9-9e9fad13c746 NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)
I'm seeking your guidance on why the service is not getting stopped or closed, and how we can avoid these errors. If these errors persist, it becomes challenging to provide users with a new device list. Your insights and suggestions will be highly appreciated.

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

Android

**Comment by sebastianhaberey** [comment]
Hi @harishkthedeveloper unfortunately I don't have the resources to take a thorough look at issues currently. 

But off the top of my head: did you know you can only have 10 "outstanding requests" on Android? As [mentioned in the plugin documentation](https://pub.dev/documentation/nsd/latest/nsd/ErrorCause.html), "outstanding requests" means running discoveries and active registrations combined.

I could be completely wrong but it might worth to check if there are any running discoveries or active service registration that need closing.

**Comment by harishkthedeveloper** [comment]
@sebastianhaberey,

I appreciate your response. I'm aware of the 10 "outstanding requests" issue. However, every time we attempt to call stopDiscovery, we encounter an exception, which I've described previously:

NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

I'm seeking guidance on how to effectively handle this error. Your assistance in resolving this matter would be greatly appreciated.

**Comment by sebastianhaberey** [comment]
I had a glimpse at your code and the video. Sadly, I can't help you here. I am not convinced this is a plugin issue, so I'm closing this.

If you still believe this is an issue with the plugin, I'd be interested in a minimal setup reproducing the error. A few lines of code that demonstrate how to make the plugin fail.
