### ISSUE TITLE
No IP info in reported services

### ISSUE THREAD

**Issue by kostadin24** [sebastianhaberey/nsd#5]
Hi, using sample I see all my services. But no IP in service info.
Am I missing something?

**Comment by sebastianhaberey** [comment]
Hi @kostadin24 do you have the dart log output or a screenshot to help me understand where you're missing the IP?

**Comment by kostadin24** [comment]
Launching lib\main.dart on Mi Note 3 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter.exampl( 3172): Late-enabling -Xcheck:jni
W/flutter.example( 3172): type=1400 audit(0.0:4324): avc: denied { read } for name="max_map_count" dev="proc" ino=820716 scontext=u:r:untrusted_app:s0:c46,c259,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
W/flutter.exampl( 3172): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/flutter.exampl( 3172): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/flutter.exampl( 3172): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/flutter.exampl( 3172): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
W/FlutterActivityAndFragmentDelegate( 3172): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:51473/t9sP0pzkMKM=/ws
Syncing files to device Mi Note 3...
I/flutter.exampl( 3172): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
[MethodChannelNsdPlatform] [2021-12-22 19:43:02.177802] [calls] Call: startDiscovery {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, service.type: _dvl-deviceapi._tcp}
[MethodChannelNsdPlatform] [2021-12-22 19:43:02.218909] [calls] Callback: onDiscoveryStartSuccessful {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2}
I/flutter ( 3172): Discovery (id: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, services: [])
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.001208] [calls] Call: startDiscovery {handle: bdaa0e36-bfd8-4752-89ba-c5b24b77d7e5, service.type: _dvl-plcnetapi._tcp}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.101779] [calls] Callback: onServiceDiscovered {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, service.name: Magic 2 WiFi 2-1, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.109619] [calls] Call: resolve {handle: f554aadd-bcb2-469e-abdc-60c002bfec2c, service.name: Magic 2 WiFi 2-1, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.537378] [calls] Callback: onServiceDiscovered {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, service.name: Magic 2 LAN 1-1, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.538583] [calls] Call: resolve {handle: d92a8587-4d81-4a4a-bd8c-277802bb60c4, service.name: Magic 2 LAN 1-1, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.540438] [calls] Callback: onServiceDiscovered {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, service.name: Magic 2 LAN 1-1 #3, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.541522] [calls] Call: resolve {handle: 8e6db8cb-6579-429f-91d8-2696cebcc680, service.name: Magic 2 LAN 1-1 #3, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.543079] [calls] Callback: onServiceDiscovered {handle: 5b5945bf-14f4-4fc8-8351-69f4f03658e2, service.name: Magic 2 LAN 1-1 #2, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.548009] [calls] Call: resolve {handle: df7f7a22-a87a-4980-94c2-b206d60e1b19, service.name: Magic 2 LAN 1-1 #2, service.type: _dvl-deviceapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:43:27.556318] [calls] Callback: onDiscoveryStartSuccessful {handle: bdaa0e36-bfd8-4752-89ba-c5b24b77d7e5}
I/flutter ( 3172): Discovery (id: bdaa0e36-bfd8-4752-89ba-c5b24b77d7e5, services: [])
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.211131] [calls] Callback: onServiceDiscovered {handle: bdaa0e36-bfd8-4752-89ba-c5b24b77d7e5, service.name: Magic 2 WiFi 2-1, service.type: _dvl-plcnetapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.214889] [calls] Call: resolve {handle: 6ab009a9-1c7f-4434-b1e4-791eab6c1d71, service.name: Magic 2 WiFi 2-1, service.type: _dvl-plcnetapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.218012] [calls] Callback: onServiceDiscovered {handle: bdaa0e36-bfd8-4752-89ba-c5b24b77d7e5, service.name: Magic 2 LAN 1-1 #2, service.type: _dvl-plcnetapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.220356] [calls] Call: resolve {handle: 0c0fdaae-13c6-495f-b36d-1c09059525c5, service.name: Magic 2 LAN 1-1 #2, service.type: _dvl-plcnetapi._tcp, service.host: null, service.port: null, service.txt: {}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.239782] [calls] Callback: onResolveSuccessful {handle: f554aadd-bcb2-469e-abdc-60c002bfec2c, service.name: Magic 2 WiFi 2-1, service.type: _dvl-deviceapi._tcp, service.host: Kids-WiFi, service.port: 14791, service.txt: {Features: [114, 101, 115, 101, 116, 44, 117, 112, 100, 97, 116, 101, 44, 108, 101, 100, 44, 105, 110, 116, 109, 116, 103, 49, 44, 119, 105, 102, 105, 49], FirmwareVersion: [53, 46, 56, 46, 53], MT: [51, 48, 56, 49], PS: [48, 120, 70], SN: [49, 56, 48, 55, 49, 56, 53, 54, 49, 49, 48, 48, 48, 49, 49, 48], Path: [49, 48, 51, 48, 51, 49, 48, 48, 53, 102, 98, 100, 99, 49, 101, 55, 47, 100, 101, 118, 105, 99, 101, 97, 112, 105], FirmwareDate: [50, 48, 50, 49, 45, 49, 48, 45, 48, 56], Product: [77, 97, 103, 105, 99, 32, 50, 32, 87, 105, 70, 105, 32, 50, 45, 49], Version: [118, 48]}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.252387] [calls] Callback: onResolveSuccessful {handle: d92a8587-4d81-4a4a-bd8c-277802bb60c4, service.name: Magic 2 LAN 1-1, service.type: _dvl-deviceapi._tcp, service.host: Kuhnia, service.port: 14791, service.txt: {Features: [105, 110, 116, 109, 116, 103, 49, 44, 108, 101, 100, 44, 114, 101, 115, 101, 116, 44, 114, 101, 115, 116, 97, 114, 116, 44, 117, 112, 100, 97, 116, 101], FirmwareVersion: [55, 46, 49, 50, 46, 48, 46, 49, 48, 50], MT: [50, 57, 57, 57], SN: [49, 56, 48, 55, 48, 52, 52, 57, 55, 48, 48, 48, 57, 55, 52, 50], Path: [117, 113, 51, 53, 85, 87, 77, 54, 114, 48, 52, 89, 51, 50, 83, 54, 47, 100, 101, 118, 105, 99, 101, 97, 112, 105], FirmwareDate: [50, 48, 50, 49, 45, 49, 50, 45, 49, 51], Product: [77, 97, 103, 105, 99, 32, 50, 32, 76, 65, 78, 32, 49, 45, 49], Version: [118, 48]}}
[MethodChannelNsdPlatform] [2021-12-22 19:44:59.255245] [calls] Callback: onResolveSuccessful {handle: 8e6db8cb-6579-429f-91d8-2696cebcc680, service.name: Magic 2 LAN 1-1 #3, service.type: _dvl-deviceapi._tcp, service.host: LANhome-ofice, service.port: 14791, service.txt: {Features: [105, 110, 116, 109, 116, 103, 49, 44, 108, 101, 100, 44, 114, 101, 115, 101, 116, 44, 114, 101, 115, 116, 97, 114, 116, 44, 117, 112, 100, 97, 116, 101], FirmwareVersion: [55, 46, 49, 50, 46, 48, 46, 49, 48, 50], MT: [50, 57, 57, 57], SN: [49, 56, 48, 55, 48, 52, 52, 57, 55, 48, 48, 48, 57, 55, 51, 57], Path: [102, 112, 113, 80, 101, 102, 110, 55, 67, 106, 105, 66, 97, 100, 84, 86, 47, 100, 101, 118, 105, 99, 101, 97, 112, 105], FirmwareDate: [50, 48, 50, 49, 45, 49, 50, 45, 49, 51], Product: [77, 97, 103, 105, 99, 32, 50, 32, 76, 65, 78, 32, 49, 45, 49], Version: [118, 48]}}
[MethodChannelNsdPlatform] null

**Comment by kostadin24** [comment]
No such field in Service class.

**Comment by sebastianhaberey** [comment]
Oh, I get it. There is no field for IP in the service class, only `host` which contains the canonical host name or `null` if the service resides on the local host. You should be able to use the host name to access the service.

**Comment by kostadin24** [comment]
Ok, thanks.
