### ISSUE TITLE
nsd 2.3.1 Not compatible uuid 4.1.0

### ISSUE THREAD

**Issue by zf8848** [sebastianhaberey/nsd#50]
Because no versions of nsd match >2.3.1 <3.0.0 and nsd 2.3.1 depends on nsd_platform_interface ^1.6.0, nsd ^2.3.1 requires nsd_platform_interface ^1.6.0.
Because nsd_platform_interface 1.6.0 depends on uuid ^3.0.7 and no versions of nsd_platform_interface match >1.6.0 <2.0.0, nsd_platform_interface ^1.6.0 requires uuid ^3.0.7.
Thus, nsd ^2.3.1 requires uuid ^3.0.7.

**Comment by sebastianhaberey** [comment]
Should be fixed in version 3.0.0. 

Please be aware that nsd 3.0.0 requires Dart SDK >= 3.0.0 and Flutter SDK >= 3.10.0.
