### ISSUE TITLE
`stopDiscovery` should `dispose()` the `Discovery`

### ISSUE THREAD

**Issue by fischerscode** [sebastianhaberey/nsd#52]
### Description

Maybe I'm missing something, but I think `stopDiscovery` should `dispose()` the `Discovery`.

*Alternatively, it should be documented, that the developer is considered to be the [object's owner](https://github.com/flutter/flutter/blob/e33d4b86270e3c012ba13d68d6e90f2eabc4912b/packages/flutter/lib/src/foundation/change_notifier.dart#L368) and should therefore dispose the `Discovery`* themself.

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

None

**Comment by sebastianhaberey** [comment]
Hi @fischerscode 

you may be right. Thing is I can't find anything in the [documentation](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) about this. There's not one word about having to dispose _ChangeNotifier_, nor is it actually disposed in the examples.

**Comment by fischerscode** [comment]
I'm used to always dispose them, since it clears the list of listeners. But to be honest, now im not sure if it's actually required, since the documentation doesn't mention it. I always assumed, it's needed to make the job of the garbage collector easier.

Might be best to ask the flutter team.

**Comment by sebastianhaberey** [comment]
I'll close this until it's established we actually _need_ to dispose _ChangeNotifier_. My understanding of Dart is that the Dart garbage collector is pretty good. Also, dispose() seems to be a Flutter mechanism that needs to be called when the documentation indicates it.

Feel free to re-open another issue if you find some official info on this (I looked but I couldn't find any).
