### ISSUE TITLE
pub.dev Changelog tab is reversed

### ISSUE THREAD

**Issue by guyluz11** [sebastianhaberey/nsd#60]
### Description

When looking at Changelog tab in [pub.dev](https://pub.dev/packages/nsd/changelog) I expect the newest version to be first, now it is the opposite

![image](https://github.com/sebastianhaberey/nsd/assets/9304740/65ef0b5b-7b10-4ee2-bc86-13b8b6063721)

### Scenario

Other (please describe above)

### Platform

None

**Comment by sebastianhaberey** [comment]
Resolved in newest version.
