### ISSUE TITLE
Messaging on non-platform thread

### ISSUE THREAD

**Issue by ToH2002** [sebastianhaberey/nsd#71]
### Description

Wen running debug sessions, I get messages like this:

> [ERROR:flutter/shell/common/shell.cc(1055)] The 'com.haberey/nsd' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
> See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
> 

Looks like something is broken in the implementation

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

Windows

**Comment by sebastianhaberey** [comment]
Yes, this is issue #46. Unfortunately, I don't have the resources to deal with it [(see here)](https://github.com/sebastianhaberey/nsd/issues/46#issuecomment-1712474875). Closing as duplicate.
